name: Zara Stok Kontrolü

on:
  schedule:
    # Bu cron job her dakika çalışır.
    - cron: '*/1 * * * *'
  workflow_dispatch: # Manuel olarak çalıştırma imkanı için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Stok Kontrol Betiğini Çalıştır
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python zara_stok_takibi.py
      
      - name: Değişiklikleri Depoya Kaydet
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add stok_durumu.txt
          # Sadece değişiklik varsa commit at
          git diff --staged --quiet || git commit -m "Stok durumu güncellendi"
          git push
